export const skills = [
  'React',
  'JavaScript',
  'NodeJS',
  'TypeScript',
  'HTML5',
  'CSS3',
  'NextJS',
  'Express',
  'C#',
  '.NET',
  'SQL',
  'noSQL',
  'Git',
  'Docker',
  'API Rest',
  'GraphQL',
  'Styled Components',
  'Bootstrap',
  'Tailwind',
  'Material UI'
];

export const works = [
  {
    title: 'Wordle Game',
    subtitle: 'React',
    description: 'Famous game to guess the hidden word using the letters and their positions. Built with React and TS',
    image: '../public/wordle-game.png',
    link: 'https://github.com/ManuelDiLena/wordle-game',
  },
  {
    title: 'Memo Pad',
    subtitle: 'React',
    description: 'Memo app in which you can create, edit and save notes, they are displayed in markdown format.',
    image: '../public/memo-pad.png',
    link: 'https://github.com/ManuelDiLena/memo-pad',
  },
  {
    title: 'E-Commerce',
    subtitle: 'React',
    description: 'E-commerce website that has a product list, cart page, checkout page, user registration and auth.',
    image: '../public/first-ecommerce.png',
    link: 'https://github.com/ManuelDiLena/first-ecommerce',
  },
  {
    title: 'Connect-4',
    subtitle: 'React',
    description: 'Traditional 4-in-a-row game to play vs the computer or two players. Built with React, JS and CSS3.',
    image: '../public/connect-4.png',
    link: 'https://github.com/ManuelDiLena/connect-4',
  },
  {
    title: 'Task App',
    subtitle: 'React',
    description: 'Traditional task app with creation and deletion, built with React, JavaScript and CSS3.',
    image: '../public/task-app.png',
    link: 'https://github.com/ManuelDiLena/task-app',
  },
  {
    title: 'World Pizza',
    subtitle: 'JavaScript',
    description: 'Pizzeria website with various sections of the business. Built with JavaScript, HTML5 and CSS3.',
    image: '../public/world-pizza.png',
    link: 'https://github.com/ManuelDiLena/world-pizza',
  },
  {
    title: 'Events App',
    subtitle: 'JavaScript',
    description: 'Application to create events with remaining days counter, made with JavaScript.',
    image: '../public/events-app.png',
    link: 'https://github.com/ManuelDiLena/events-app',
  },
  {
    title: 'Virtual Keyboard',
    subtitle: 'JavaScript',
    description: 'Virtual keyboard created with JavaScript, HTML and CSS, with all its features.',
    image: '../public/virtual-keyboard.png',
    link: 'https://github.com/ManuelDiLena/virtual-keyboard',
  }
]